"""initial schema

Revision ID: ee3f49d5d169
Revises: 
Create Date: 2026-04-05 18:04:34.832790

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ee3f49d5d169'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('join_slug', sa.String(length=64), nullable=False),
    sa.Column('join_code', sa.String(length=12), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_language', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ENDED', name='session_status'), nullable=False),
    sa.Column('audio_transport', sa.Enum('WEBSOCKET_CHUNKS', 'WEBRTC', name='audio_transport'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_created_by_user_id'), 'sessions', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_join_code'), 'sessions', ['join_code'], unique=True)
    op.create_index(op.f('ix_sessions_join_slug'), 'sessions', ['join_slug'], unique=True)
    op.create_index(op.f('ix_sessions_status'), 'sessions', ['status'], unique=False)
    op.create_table('session_languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('language_code', sa.String(length=16), nullable=False),
    sa.Column('tts_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'language_code', name='uq_session_language')
    )
    op.create_index(op.f('ix_session_languages_session_id'), 'session_languages', ['session_id'], unique=False)
    op.create_table('transcript_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=True),
    sa.Column('end_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'sequence', name='uq_transcript_session_sequence')
    )
    op.create_index(op.f('ix_transcript_segments_session_id'), 'transcript_segments', ['session_id'], unique=False)
    op.create_index('ix_transcript_session_created', 'transcript_segments', ['session_id', 'created_at'], unique=False)
    op.create_table('usage_meters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_meters_period'), 'usage_meters', ['period'], unique=False)
    op.create_index(op.f('ix_usage_meters_provider'), 'usage_meters', ['provider'], unique=False)
    op.create_index(op.f('ix_usage_meters_session_id'), 'usage_meters', ['session_id'], unique=False)
    op.create_index('ix_usage_period_provider', 'usage_meters', ['period', 'provider'], unique=False)
    op.create_table('translation_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('transcript_segment_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transcript_segment_id'], ['transcript_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transcript_segment_id', 'language_code', name='uq_translation_transcript_language')
    )
    op.create_index(op.f('ix_translation_segments_session_id'), 'translation_segments', ['session_id'], unique=False)
    op.create_index(op.f('ix_translation_segments_transcript_segment_id'), 'translation_segments', ['transcript_segment_id'], unique=False)
    op.create_index('ix_translation_session_lang_created', 'translation_segments', ['session_id', 'language_code', 'created_at'], unique=False)
    # ### end Alembic commands ###

    # Seed canonical roles.
    op.bulk_insert(
        sa.table(
            "roles",
            sa.column("name", sa.String),
            sa.column("description", sa.String),
        ),
        [
            {"name": "admin", "description": "Full system access"},
            {"name": "operator", "description": "Create and run sessions"},
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_translation_session_lang_created', table_name='translation_segments')
    op.drop_index(op.f('ix_translation_segments_transcript_segment_id'), table_name='translation_segments')
    op.drop_index(op.f('ix_translation_segments_session_id'), table_name='translation_segments')
    op.drop_table('translation_segments')
    op.drop_index('ix_usage_period_provider', table_name='usage_meters')
    op.drop_index(op.f('ix_usage_meters_session_id'), table_name='usage_meters')
    op.drop_index(op.f('ix_usage_meters_provider'), table_name='usage_meters')
    op.drop_index(op.f('ix_usage_meters_period'), table_name='usage_meters')
    op.drop_table('usage_meters')
    op.drop_index('ix_transcript_session_created', table_name='transcript_segments')
    op.drop_index(op.f('ix_transcript_segments_session_id'), table_name='transcript_segments')
    op.drop_table('transcript_segments')
    op.drop_index(op.f('ix_session_languages_session_id'), table_name='session_languages')
    op.drop_table('session_languages')
    op.drop_index(op.f('ix_sessions_status'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_join_slug'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_join_code'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_created_by_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
    sa.Enum(name='audio_transport').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='session_status').drop(op.get_bind(), checkfirst=False)
